[package]
name = "strake-connectors"
version.workspace = true
license.workspace = true
edition = "2024"

[features]
# experimental-iceberg = ["dep:iceberg", "dep:iceberg-catalog-rest", "dep:iceberg-datafusion"]
experimental-iceberg = ["dep:iceberg", "dep:iceberg-catalog-rest", "dep:iceberg-datafusion"]

[dependencies]
strake-common = { path = "../common" }
strake-error = { path = "../error", features = ["datafusion"] }
strake-sql = { path = "../sql" }
datafusion = { workspace = true }
datafusion-table-providers = { workspace = true }
datafusion-federation = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
globset = "0.4"
parquet = { workspace = true }
datafusion-datasource = { workspace = true }
datafusion-datasource-parquet = { workspace = true }
# datafusion-catalog = "53.0.0"
bytes = "1.6"
object_store = { workspace = true, features = ["aws"] }

# Connectors
duckdb = { version = "1.10501.0", features = ["bundled", "vtab-arrow", "r2d2"], default-features = false }
r2d2 = "0.8"
tokio-postgres = { workspace = true }
postgres-types = { workspace = true }
rust_decimal = { workspace = true }
mysql_async = "0.36.1"
rusqlite = { version = "0.37", features = ["bundled"] }
# object_store = "0.12.4" moved to workspace above
opendal = { git = "https://github.com/apache/opendal", branch = "main", features = ["services-s3", "services-azblob", "services-gcs", "services-http", "services-ftp"] }
object_store_opendal = { git = "https://github.com/apache/opendal", branch = "main" }
jsonwebtoken = { workspace = true }
base64 = "0.22"
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
rand = "0.9.2"
arrow = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
futures = { workspace = true }
arrow-flight = { workspace = true }
tower = { workspace = true }
prost-reflect = { version = "0.16", features = ["serde"] }
moka = { version = "0.12", features = ["future"] }
chrono = "0.4"
rust-oracle = { workspace = true }
bb8 = { workspace = true }
bb8-oracle = { workspace = true }
# Apache Iceberg integration
iceberg = { git = "https://github.com/apache/iceberg-rust", branch = "main", optional = true }
iceberg-catalog-rest = { git = "https://github.com/apache/iceberg-rust", branch = "main", optional = true }
iceberg-datafusion = { git = "https://github.com/apache/iceberg-rust", branch = "main", optional = true }
aws-config = "1.8.14"
aws-credential-types = "1.2.12"
dashmap = "6.1.0"
roaring = "0.10.12"

[dev-dependencies]
wiremock = "0.6"
tempfile = "3.10"
tokio-test = "0.4"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
strake-runtime = { path = "../runtime" }
