from typing import Type

class StrakeException(Exception): ...
class ConnectionError(StrakeException): ...
class QueryError(StrakeException): ...
class ConfigError(StrakeException): ...
class AuthError(StrakeException): ...
class InternalError(StrakeException): ...
